#pragma once

enum GFX_TEXTURE_TYPE
{
	GFX_TEXTURE_DIFFUSE,
	GFX_TEXTURE_SPECULAR,
	GFX_TEXTURE_NORMAL,

	GFX_TEXTURE_TYPE_COUNT,
};


#define ENUM_COUNT( x ) x##_COUNT, x##_COUNT_STEPBACK = x##_COUNT - 1,


enum GFX_TEXTURE_SLOTS
{
	GFX_TEXTURE_SLOT_DIFFUSE0,
	ENUM_COUNT( GFX_TEXTURE_SLOT_DIFFUSE )

	GFX_TEXTURE_SLOT_SPECULAR0,
	ENUM_COUNT ( GFX_TEXTURE_SLOT_SPECULAR )

	GFX_TEXTURE_SLOT_NORMAL,

	GFX_TEXTURE_SLOT_COUNT,
};


enum GFX_TEX_FORMATS
{
	GFX_TEX_FORMAT_R,
	GFX_TEX_FORMAT_RGB,
	GFX_TEX_FORMAT_RGBA,
	GFX_TEX_FORMAT_BC1,
	GFX_TEX_FORMAT_BC3,
	GFX_TEX_FORMAT_BC4,
	GFX_TEX_FORMAT_BC5,

	GFX_TEX_FORMAT_COUNT,
};


enum GFX_TEX_PIXEL_SIZE // in bits
{
	GFX_TEX_PIXEL_SIZE_R = 8,
	GFX_TEX_PIXEL_SIZE_RGB = 24,
	GFX_TEX_PIXEL_SIZE_RGBA = 32,
	GFX_TEX_PIXEL_SIZE_BC1 = 4,
	GFX_TEX_PIXEL_SIZE_BC3 = 8,
	GFX_TEX_PIXEL_SIZE_BC4 = 4,
	GFX_TEX_PIXEL_SIZE_BC5 = 8,

	GFX_TEX_PIXEL_SIZE_COUNT,
};