#pragma once

enum GFX_TEXTURE_TYPE
{
	GFX_TEXTURE_DIFFUSE,
	GFX_TEXTURE_SPECULAR,
	GFX_TEXTURE_NORMAL,

	GFX_TEXTURE_TYPE_COUNT,
};


#define ENUM_COUNT( x ) x##_COUNT, x##_COUNT_STEPBACK = x##_COUNT - 1,


enum GFX_TEXTURE_SLOTS
{
	GFX_TEXTURE_SLOT_DIFFUSE0,
	ENUM_COUNT( GFX_TEXTURE_SLOT_DIFFUSE )

	GFX_TEXTURE_SLOT_SPECULAR0,
	ENUM_COUNT ( GFX_TEXTURE_SLOT_SPECULAR )

	GFX_TEXTURE_SLOT_NORMAL,

	GFX_TEXTURE_SLOT_COUNT,
};
